#!/bin/sh

set -e

TMPDIR=$(mktemp -d)

cat | awk -v TMPDIR=${TMPDIR} '{ OUTPUT=TMPDIR "/kustomize." (N++) ".yaml" } {print "---" > OUTPUT } {print >> OUTPUT }' RS='---'
for f in ${TMPDIR}/*.yaml
do
  if cat $f | grep -q "^sops:"; then
    echo "---"
    sops --ignore-mac -d $f 2> /dev/null
  else
    cat $f
  fi
done

rm -rf $TMPDIl
